fix: moved coveralls to workflow (#44)
* fix: moved coveralls to workflow

* fix: Could not find SimpleCov Profile called 'ruby'

* fix: LcovFormatter failed with NoMethodError: undefined method `branch_coverage?' for SimpleCov:Module

* fix: simplecov (~> 0.21) was resolved to 0.21.2, which depends on ruby (>= 2.5.0)

* fix: error from lcovParse: ' 'Failed to parse string

* fix: error from lcovParse: ' 'Failed to parse string

* fix: simplecov (~> 0.20) was resolved to 0.21.2

* fix: simplecov (~> 0.18) was resolved to 0.18.5, which depends on Ruby (>= 2.4.0)

* fix: simplecov (~> 0.21) was resolved to 0.21.2, which depends on Ruby (>= 2.5.0)